services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: sistema-ticket-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistema-ticket
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/backend/prisma/migrations:/docker-entrypoint-initdb.d/migrations
    ports:
      - "5447:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sistema-ticket"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API (NestJS + Prisma)
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: development
    container_name: sistema-ticket-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3012:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sistema-ticket?schema=public
      - JWT_SECRET=dev_jwt_secret_change_me
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./apps/backend:/app/apps/backend
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate dev --name init &&
             npm run start:dev"

  # Frontend (SvelteKit)
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: development
    container_name: sistema-ticket-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3012/api
    volumes:
      - ./apps/frontend:/app/apps/frontend
    command: >
      sh -c "npm run dev -- --host 0.0.0.0 --port 5173"

volumes:
  postgres_data:
